package com.valu.uitaycompose.utils

const val UI_TAY_TEXT_DEFAULT = "TAY LIBRARY"
const val UI_EMPTY = ""
const val UI_TAY_TAG = "UI_TAY_TAG"


const val UI_TITLE_BIOMETRIC = "Validacion biometrica"
const val UI_SUB_TITLE_BIOMETRIC = "Ingresa tu huella digital"
const val UI_CANCEL_BIOMETRIC = "Cancelar"
const val UI_MY_KEY_SECRET = "my_key_secret_aes"
const val UI_MY_KEY_SECRET_RSA = "my_key_secret_rsa"
const val UI_ERROR_KEY = "The key must have 16, 24, or 32 characters."
const val UI_ERROR_KEY_FORMAT = "The string is neither valid Hexadecimal nor Base64"
const val UI_TAY_ERROR = "Ocurrio un error"
const val UI_TAY_FORMAT_DATE = "dd/MM/yyyy"
const val UI_TAY_FORMAT_MONTH = "MMMM yyyy"
const val UI_TAY_FORMAT_NAME_DAY = "EEEE"
const val UI_TAY_DIALOG_TITLE = "Cerrar sesión"
const val UI_TAY_DIALOG_SUB_TITLE = "Estas seguro que deseas cerrar sesión"
const val UI_TAY_DIALOG_ACCEPT = "Aceptar"
const val UI_TAY_DIALOG_CANCEL = "Cancelar"
const val HOUR_START_DEFAULT = "09:00:00"
const val HOUR_END_DEFAULT = "21:00:00"
const val COUNTRY_DEFAULT = "PE"
const val COUNTRY_AR = "AR"
const val COUNTRY_MX = "MX"
const val COUNTRY_CODE_PE = "+51"
const val COUNTRY_CODE_AR = "+549"
const val COUNTRY_CODE_MX = "+52"
const val SIZE_REGULAR = "R"
const val SIZE_NORMAL = "N"
const val SIZE_MEDIUM = "M"
const val SIZE_BIG = "B"
const val TYPE_CONSULT = "CONSULTA"
const val TAY_LOG  = "TAY_LOG"
const val ERROR_QR_IMG = "No se encontró ningún QR en la imagen tras intentar todos los formatos"
const val ERROR_TRY_ORIENTATION = "Exception when trying to orient image"

